name: 'build and push docker image'
on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths-ignore:
      - '*.md'

permissions:
  contents: read

env:
  GH_USER: 'erikbjo'
  DOCKER_PAT: ${{ secrets.DOCKER_PAT }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    name: 'build and push'
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ env.GH_USER }}
          password: ${{ env.DOCKER_PAT }}

      - name: 'Set up QEMU'
        uses: docker/setup-qemu-action@v3

      - name: 'Set up Docker Buildx'
        uses: docker/setup-buildx-action@v3

      - name: 'Build and push'
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/${{ env.GH_USER }}/website:latest
